const newsInfo = [
  {
    type: 'internship',
    imgSrc: 'img/news-mobile-1@1x.png',
    imgSrcset: 'img/news-mobile-1@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.webp 1x, img/news-desktop-1@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.png 1x, img/news-desktop-1@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.webp 1x, img/news-tablet-1@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.png 1x, img/news-tablet-1@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-1@1x.webp 1x, img/news-mobile-1@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография участницы программы стажировки.',
    title: 'Интервью с участницей программы стажировки',
    description: 'Саша рассказывает, как попала в программу и как прошла 6-месячная стажировка в ISOFound',
    date: '23/03/2023',
  },
  {
    type: 'travel',
    imgSrc: 'img/news-mobile-2@1x.png',
    imgSrcset: 'img/news-mobile-2@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.webp 1x, img/news-desktop-2@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.png 1x, img/news-desktop-2@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.webp 1x, img/news-tablet-2@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.png 1x, img/news-tablet-2@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-2@1x.webp 1x, img/news-mobile-2@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография пляжа.',
    title: 'Путешествуем по миру',
    description: 'Какие места посещают наши студенты весной',
    date: '20/03/2023',
  },
  {
    type: 'volunteering',
    imgSrc: 'img/news-mobile-3@1x.png',
    imgSrcset: 'img/news-mobile-3@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.webp 1x, img/news-desktop-3@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.png 1x, img/news-desktop-3@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.webp 1x, img/news-tablet-3@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.png 1x, img/news-tablet-3@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-3@1x.webp 1x, img/news-mobile-3@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Девушка в оранжевой футболке со значком волонтёра.',
    title: 'Новая программа волонтёрства',
    description: 'Программа помощи детям длительностью 4 месяца',
    date: '17/03/2023',
  },
  {
    type: 'career',
    imgSrc: 'img/news-mobile-4@1x.png',
    imgSrcset: 'img/news-mobile-4@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.webp 1x, img/news-desktop-4@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.png 1x, img/news-desktop-4@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.webp 1x, img/news-tablet-4@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.png 1x, img/news-tablet-4@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-4@1x.webp 1x, img/news-mobile-4@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Рабочее место.',
    title: 'Построй свою карьеру',
    description: 'Ведущие компании готовы трудоустроить выпускников стажировки',
    date: '10/03/2023',
  },
  {
    type: 'internship',
    imgSrc: 'img/news-mobile-1@1x.png',
    imgSrcset: 'img/news-mobile-1@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.webp 1x, img/news-desktop-1@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.png 1x, img/news-desktop-1@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.webp 1x, img/news-tablet-1@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.png 1x, img/news-tablet-1@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-1@1x.webp 1x, img/news-mobile-1@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография участницы программы стажировки.',
    title: 'Интервью с участницей программы стажировки',
    description: 'Саша рассказывает, как попала в программу и как прошла 6-месячная стажировка в ISOFound',
    date: '23/03/2023',
  },
  {
    type: 'travel',
    imgSrc: 'img/news-mobile-2@1x.png',
    imgSrcset: 'img/news-mobile-2@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.webp 1x, img/news-desktop-2@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.png 1x, img/news-desktop-2@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.webp 1x, img/news-tablet-2@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.png 1x, img/news-tablet-2@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-2@1x.webp 1x, img/news-mobile-2@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография пляжа.',
    title: 'Путешествуем по миру',
    description: 'Какие места посещают наши студенты весной',
    date: '20/03/2023',
  },
  {
    type: 'volunteering',
    imgSrc: 'img/news-mobile-3@1x.png',
    imgSrcset: 'img/news-mobile-3@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.webp 1x, img/news-desktop-3@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.png 1x, img/news-desktop-3@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.webp 1x, img/news-tablet-3@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.png 1x, img/news-tablet-3@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-3@1x.webp 1x, img/news-mobile-3@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Девушка в оранжевой футболке со значком волонтёра.',
    title: 'Новая программа волонтёрства',
    description: 'Программа помощи детям длительностью 4 месяца',
    date: '17/03/2023',
  },
  {
    type: 'career',
    imgSrc: 'img/news-mobile-4@1x.png',
    imgSrcset: 'img/news-mobile-4@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.webp 1x, img/news-desktop-4@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.png 1x, img/news-desktop-4@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.webp 1x, img/news-tablet-4@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.png 1x, img/news-tablet-4@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-4@1x.webp 1x, img/news-mobile-4@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Рабочее место.',
    title: 'Построй свою карьеру',
    description: 'Ведущие компании готовы трудоустроить выпускников стажировки',
    date: '10/03/2023',
  },
  {
    type: 'internship',
    imgSrc: 'img/news-mobile-1@1x.png',
    imgSrcset: 'img/news-mobile-1@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.webp 1x, img/news-desktop-1@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.png 1x, img/news-desktop-1@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.webp 1x, img/news-tablet-1@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.png 1x, img/news-tablet-1@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-1@1x.webp 1x, img/news-mobile-1@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография участницы программы стажировки.',
    title: 'Интервью с участницей программы стажировки',
    description: 'Саша рассказывает, как попала в программу и как прошла 6-месячная стажировка в ISOFound',
    date: '23/03/2023',
  },
  {
    type: 'travel',
    imgSrc: 'img/news-mobile-2@1x.png',
    imgSrcset: 'img/news-mobile-2@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.webp 1x, img/news-desktop-2@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.png 1x, img/news-desktop-2@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.webp 1x, img/news-tablet-2@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.png 1x, img/news-tablet-2@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-2@1x.webp 1x, img/news-mobile-2@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография пляжа.',
    title: 'Путешествуем по миру',
    description: 'Какие места посещают наши студенты весной',
    date: '20/03/2023',
  },
  {
    type: 'volunteering',
    imgSrc: 'img/news-mobile-3@1x.png',
    imgSrcset: 'img/news-mobile-3@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.webp 1x, img/news-desktop-3@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.png 1x, img/news-desktop-3@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.webp 1x, img/news-tablet-3@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.png 1x, img/news-tablet-3@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-3@1x.webp 1x, img/news-mobile-3@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Девушка в оранжевой футболке со значком волонтёра.',
    title: 'Новая программа волонтёрства',
    description: 'Программа помощи детям длительностью 4 месяца',
    date: '17/03/2023',
  },
  {
    type: 'career',
    imgSrc: 'img/news-mobile-4@1x.png',
    imgSrcset: 'img/news-mobile-4@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.webp 1x, img/news-desktop-4@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.png 1x, img/news-desktop-4@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.webp 1x, img/news-tablet-4@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.png 1x, img/news-tablet-4@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-4@1x.webp 1x, img/news-mobile-4@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Рабочее место.',
    title: 'Построй свою карьеру',
    description: 'Ведущие компании готовы трудоустроить выпускников стажировки',
    date: '10/03/2023',
  },
  {
    type: 'internship',
    imgSrc: 'img/news-mobile-1@1x.png',
    imgSrcset: 'img/news-mobile-1@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.webp 1x, img/news-desktop-1@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-1@1x.png 1x, img/news-desktop-1@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.webp 1x, img/news-tablet-1@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-1@1x.png 1x, img/news-tablet-1@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-1@1x.webp 1x, img/news-mobile-1@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография участницы программы стажировки.',
    title: 'Интервью с участницей программы стажировки',
    description: 'Саша рассказывает, как попала в программу и как прошла 6-месячная стажировка в ISOFound',
    date: '23/03/2023',
  },
  {
    type: 'travel',
    imgSrc: 'img/news-mobile-2@1x.png',
    imgSrcset: 'img/news-mobile-2@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.webp 1x, img/news-desktop-2@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-2@1x.png 1x, img/news-desktop-2@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.webp 1x, img/news-tablet-2@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-2@1x.png 1x, img/news-tablet-2@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-2@1x.webp 1x, img/news-mobile-2@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Фотография пляжа.',
    title: 'Путешествуем по миру',
    description: 'Какие места посещают наши студенты весной',
    date: '20/03/2023',
  },
  {
    type: 'volunteering',
    imgSrc: 'img/news-mobile-3@1x.png',
    imgSrcset: 'img/news-mobile-3@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.webp 1x, img/news-desktop-3@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-3@1x.png 1x, img/news-desktop-3@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.webp 1x, img/news-tablet-3@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-3@1x.png 1x, img/news-tablet-3@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-3@1x.webp 1x, img/news-mobile-3@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Девушка в оранжевой футболке со значком волонтёра.',
    title: 'Новая программа волонтёрства',
    description: 'Программа помощи детям длительностью 4 месяца',
    date: '17/03/2023',
  },
  {
    type: 'career',
    imgSrc: 'img/news-mobile-4@1x.png',
    imgSrcset: 'img/news-mobile-4@2x.png 2x',
    sourceSrcset: [
      {
        id: 0,
        type: 'image/webp',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.webp 1x, img/news-desktop-4@2x.webp 2x',
        width: '604',
        height: '400',
      },
      {
        id: 1,
        type: 'image/png',
        media: '(min-width: 1440px)',
        srcset: 'img/news-desktop-4@1x.png 1x, img/news-desktop-4@2x.png 2x',
        width: '604',
        height: '400',
      },
      {
        id: 2,
        type: 'image/webp',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.webp 1x, img/news-tablet-4@2x.webp 2x',
        width: '324',
        height: '350',
      },
      {
        id: 3,
        type: 'image/png',
        media: '(min-width: 768px)',
        srcset: 'img/news-tablet-4@1x.png 1x, img/news-tablet-4@2x.png 2x',
        width: '324',
        height: '350',
      },
      {
        id: 4,
        type: 'image/webp',
        media: '',
        srcset: 'img/news-mobile-4@1x.webp 1x, img/news-mobile-4@2x.webp 2x',
        width: '290',
        height: '330',
      },
    ],
    imgAlt: 'Рабочее место.',
    title: 'Построй свою карьеру',
    description: 'Ведущие компании готовы трудоустроить выпускников стажировки',
    date: '10/03/2023',
  },
];

export {newsInfo};
